# Generated by Django 4.2 on 2023-04-30 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(
                    '^[&0-9a-zA-Z\\s_\\.\\,-]+$', 'Only alphanumeric characters, and ,.-_& are allowed.')])),
            ],
        ),
    ]
