# Generated by Django 4.2 on 2023-04-18 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('poll', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=40)),
                ('max_participants', models.PositiveIntegerField()),
                ('participants_num', models.PositiveIntegerField(default=1)),
                ('start_time', models.DateTimeField(verbose_name='Event Starting Time')),
                ('end_time', models.DateTimeField(verbose_name='Event End Time')),
                ('is_private', models.BooleanField(default=False)),
                (
                    'category',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='category.category',
                    ),
                ),
                (
                    'location',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='location.location',
                    ),
                ),
                (
                    'poll',
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.poll'
                    ),
                ),
            ],
        ),
    ]
