# Generated by Django 4.2 on 2023-04-29 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('teams', '0001_initial'),
        ('event', '0002_userevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='teamID',
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.teams'
            ),
        ),
    ]
