# Generated by Django 4.2 on 2023-05-03 07:35

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_userevent_teamid'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
