# Generated by Django 4.1.7 on 2023-04-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('poll_id', models.ForeignKey(to='poll.Poll', on_delete=models.CASCADE)),
            ],
        ),
    ]
