# Generated by Django 4.2 on 2023-04-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('poll_suggestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPollSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    to='poll_suggestion.pollsuggestion')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
