# Generated by Django 4.1.7 on 2023-04-17 14:57

from django.db import migrations, models
import poll.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('max_suggestions', models.PositiveIntegerField()),
                ('end_time', models.DateTimeField(default=poll.models.get_default_end_date)),
            ],
        ),
    ]
