# Generated by Django 4.2 on 2023-04-24 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_userevent'),
        ('poll', '0002_poll_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='event_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='poll_ref', to='event.event'),
        ),
    ]
